Trainee scripts
TMyza/sdl_atf_test_scripts pull request #1
Opened 2018-08-01 06:55 UTC by TMyza

Pull request.

2018-08-01 07:20 UTC, GetmanetsIrina requested changes

2018-08-01 07:20 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +local function sendGetVehicleData(param)
There is internal rule - name params in function with first character 'p', in your case - local function sendGetVehicleData(pParam), please perform update across all scripts.

2018-08-01 07:20 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +local function sendGetVehicleData(param)
This function is common for some scripts, so move it to common file. 
Perform update across all scripts.

2018-08-01 07:20 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +    runner.Step("Send GetVehicleData" .. " " ..  v .. " = " .. tostring(value), sendGetVehicleData, { v })
"Send GetVehicleData" .. " " ..  v .. " = " .. tostring(value) ->"Send GetVehicleData " ..  v .. " = " .. tostring(value)

2018-08-01 07:20 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +runner.Step("Stop SDL", common.postconditions)
add empty line in the end of file, across all files

2018-08-01 07:20 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/002_Get_Vehicle_Data_Negative_DOP.lua
> +local function sendGetVehicleData(param)
move to common.

2018-08-01 07:20 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/002_Get_Vehicle_Data_Negative_DOP.lua
> +    runner.Step("Send GetVehicleData" .. " " ..  v .. " = " .. tostring(value), sendGetVehicleData, { v })
runner.Step("Send GetVehicleData " ..  v .. " = " .. tostring(value)

2018-08-01 07:20 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/003_Get_Vehicle_Data_Positive_with_empty_value_DOP.lua
> +    gpsData[param] = value
In this script request can be empty

2018-08-01 12:59 UTC, GetmanetsIrina requested changes

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +-- Mob app sends request GetVehicleData to SDL with gps parametr = true
Better write the list with numbering:
In case:
1. Mob app sends request GetVehicleData to SDL with gps parametr = true
2. SDL resend this request to HMI with gps parameter = true
...
SDL does:
1. Resend response to Mob App with parameters "vdop, hdop, vdop = 1000"

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +-- SDL resend this request to HMI with gps parameter = true
SDL resends

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/commonDOP.lua
> +local utils = require("user_modules/utils")
utils is not used, so must be removed.

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/commonDOP.lua
> +function m.sendGetVehicleDataPositive(pParam, value)
The same comment as for pParam, value is parameter of function, so must be pValue.
Comment is related to all functions in file.

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +-- "pdop", "hdop", "vdop"
Do not understand for what this line here.

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +-- HMI sends response with "vdop, hdop, vdop = 1000" to SDL
Better something like HMI sends response with value 1000 for parameters: vdop, hdop, vdop

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +    runner.Step("Send GetVehicleData" .. v .. "=" .. tostring(value), common.sendGetVehicleDataPositive, { v, value })
Missed space after GetVehicleData - "Send GetVehicleData "

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/002_Get_Vehicle_Data_Negative_DOP.lua
> +-- Respond GENERIC_ERROR to Mob App
Respond GENERIC_ERROR resultCode to Mob App

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/001_Get_Vehicle_Data_Positive_DOP.lua
> +local value = 1000
missed --[[ Local Variables ]] :
```
--[[ Local Variables ]] 
local value = 1000 
```

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/002_Get_Vehicle_Data_Negative_DOP.lua
> +-- "pdop", "hdop", "vdop"
remove line

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/003_Get_Vehicle_Data_Positive_with_empty_value_DOP.lua
> +local value = nil
In test response from HMI will be sent with empty gps data, so initial data must contain all params: pdop, vdop, hdop

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/004_Subscribe_Vehicle_Data_Positive_DOP.lua
> +-- Mob app subscribe to gps data
Mob app is subscribed to gps data

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/004_Subscribe_Vehicle_Data_Positive_DOP.lua
> +-- HMI sends notification OnVehicleInfoData with parameters "vdop, hdop, vdop = 1000" to SDL
see comment regarding line in first scripts

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/004_Subscribe_Vehicle_Data_Positive_DOP.lua
> +local value = 1000
see comment above

2018-08-01 12:59 UTC, GetmanetsIrina commented on test_scripts/Trainee/Updatting_DOP_value/004_Subscribe_Vehicle_Data_Positive_DOP.lua
> +local function sendOnVehicleData(pParam)
function is the same as common.sendOnVehicleDataPositive, is not?

2018-08-03 07:42 UTC, TMyza commented on test_scripts/Trainee/Updatting_DOP_value/004_Subscribe_Vehicle_Data_Positive_DOP.lua
> +local value = 1000
@GetmanetsIrina please take a look commit https://github.com/TMyza/sdl_atf_test_scripts/pull/1/commits/a3261e38fe2c055dd3f4d8747123c1d226525725

2018-08-28 14:23 UTC, closed without merging